/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drum_machine;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Morgan
 */
public class frmMPC extends javax.swing.JFrame {
    public static ActionListener AL = new AL();
    public static KeyListener KL = new KL();
    public static ActionListener CC = new ColorChange();
    /**
     * Creates new form frmMPC
     */
    public frmMPC() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setTitle("Drum Machine Project");
        this.jPad1.addKeyListener(KL);
        this.jPad1.addActionListener(AL);
        this.jPad2.addActionListener(AL);
        this.jPad3.addActionListener(AL);
        this.jPad4.addActionListener(AL);
        this.jPad5.addActionListener(AL);
        this.jPad6.addActionListener(AL);
        this.jPad7.addActionListener(AL);
        this.jPad8.addActionListener(AL);
        this.jPad9.addActionListener(AL);
        /*
        this.jPad1.addActionListener(CC);
        this.jPad2.addActionListener(CC);
        this.jPad3.addActionListener(CC);
        this.jPad4.addActionListener(CC);
        this.jPad5.addActionListener(CC);
        this.jPad6.addActionListener(CC);
        this.jPad7.addActionListener(CC);
        this.jPad8.addActionListener(CC);
        this.jPad9.addActionListener(CC);
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPad1 = new javax.swing.JButton();
        jPad2 = new javax.swing.JButton();
        jPad3 = new javax.swing.JButton();
        jPad5 = new javax.swing.JButton();
        jPad6 = new javax.swing.JButton();
        jPad4 = new javax.swing.JButton();
        jPad8 = new javax.swing.JButton();
        jPad9 = new javax.swing.JButton();
        jPad7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPad1.setText("Pad 1");
        jPad1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPad1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPad1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPad1MouseReleased(evt);
            }
        });
        jPad1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPad1KeyPressed(evt);
            }
        });

        jPad2.setText("Pad 2");
        jPad2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPad2MouseClicked(evt);
            }
        });

        jPad3.setText("Pad 3");
        jPad3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPad3MouseClicked(evt);
            }
        });

        jPad5.setText("Pad 5");
        jPad5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPad5MouseClicked(evt);
            }
        });

        jPad6.setText("Pad 6");
        jPad6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPad6MouseClicked(evt);
            }
        });

        jPad4.setText("Pad 4");
        jPad4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPad4MouseClicked(evt);
            }
        });

        jPad8.setText("Pad 8");
        jPad8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPad8MouseClicked(evt);
            }
        });
        jPad8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPad8ActionPerformed(evt);
            }
        });

        jPad9.setText("Pad 9");
        jPad9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPad9MouseClicked(evt);
            }
        });

        jPad7.setText("Pad 7");
        jPad7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPad7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPad1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPad4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPad7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPad2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPad5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPad8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPad9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPad6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPad3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPad1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPad2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPad3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPad5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPad4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPad6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPad7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPad9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPad8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        
        
    }//GEN-LAST:event_formWindowOpened

    private void jPad1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPad1MouseClicked
        
        //this.jPad1.addActionListener(AL);
    }//GEN-LAST:event_jPad1MouseClicked

    private void jPad1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPad1MousePressed
        
        
    }//GEN-LAST:event_jPad1MousePressed

    private void jPad2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPad2MouseClicked
        //Drum_Machine.playsound(2);
        //this.jPad2.addActionListener(AL);
        //this.jPad2.addActionListener(AL);
    }//GEN-LAST:event_jPad2MouseClicked

    private void jPad3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPad3MouseClicked
        //Drum_Machine.playsound(3);
        //this.jPad3.addActionListener(AL);
    }//GEN-LAST:event_jPad3MouseClicked

    private void jPad4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPad4MouseClicked
        //Drum_Machine.playsound(4);
        //this.jPad4.addActionListener(AL);
    }//GEN-LAST:event_jPad4MouseClicked

    private void jPad5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPad5MouseClicked
        //Drum_Machine.playsound(5);
        //this.jPad5.addActionListener(AL);
    }//GEN-LAST:event_jPad5MouseClicked

    private void jPad6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPad6MouseClicked
        //Drum_Machine.playsound(6);
        //this.jPad6.addActionListener(AL);
    }//GEN-LAST:event_jPad6MouseClicked

    private void jPad7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPad7MouseClicked
        //Drum_Machine.playsound(7);
        //this.jPad7.addActionListener(AL);
    }//GEN-LAST:event_jPad7MouseClicked

    private void jPad8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPad8MouseClicked
        //Drum_Machine.playsound(8);
        //this.jPad8.addActionListener(AL);
    }//GEN-LAST:event_jPad8MouseClicked

    private void jPad9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPad9MouseClicked
        //Drum_Machine.playsound(9);
        //this.jPad9.addActionListener(AL);
    }//GEN-LAST:event_jPad9MouseClicked

    private void jPad1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPad1KeyPressed

        if (evt.getKeyChar() == '1') {
            Drum_Machine.pad=this.jPad1;
        }
        switch(evt.getKeyChar()) {
            case '1':
                Drum_Machine.pad = this.jPad1;
                break;
            case '2':
                Drum_Machine.pad = this.jPad2;
                break;
            case '3':
                Drum_Machine.pad = this.jPad3;
                break;
            case '4':
                Drum_Machine.pad = this.jPad4;
                break;
            case '5':
                Drum_Machine.pad = this.jPad5;
                break;
            case '6':
                Drum_Machine.pad = this.jPad6;
                break;
            case '7':
                Drum_Machine.pad = this.jPad7;
                break;
            case '8':
                Drum_Machine.pad = this.jPad8;
                break;
            case '9':
                Drum_Machine.pad = this.jPad9;
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jPad1KeyPressed
    
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        
    }//GEN-LAST:event_formKeyPressed

    private void jPad8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPad8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPad8ActionPerformed

    private void jPad1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPad1MouseReleased
      
    }//GEN-LAST:event_jPad1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMPC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jPad1;
    public javax.swing.JButton jPad2;
    public javax.swing.JButton jPad3;
    public javax.swing.JButton jPad4;
    public javax.swing.JButton jPad5;
    public javax.swing.JButton jPad6;
    public javax.swing.JButton jPad7;
    public javax.swing.JButton jPad8;
    public javax.swing.JButton jPad9;
    // End of variables declaration//GEN-END:variables
}
